config/routes.rb
Hive::Application.routes.draw do
  resources :kpi_cou_rels

  resources :types

  resources :kpis

  resources :counters

  resources :vendors

  resources :measurements

  resources :adapters do
	resources :measurements
  end

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @type }
      else
        format.html { render action: 'new' }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:ty_id, :ty_name)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ty_name %><br>
    <%= f.text_field :ty_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Listing types</h1>

<table>
  <thead>
    <tr>
      <th>Ty</th>
      <th>Ty name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.id %></td>
        <td><%= type.ty_name %></td>
        <td><%= link_to 'Show', type %></td>
        <td><%= link_to 'Edit', edit_type_path(type) %></td>
        <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ty:</strong>
  <%= @type.id %>
</p>

<p>
  <strong>Ty name:</strong>
  <%= @type.ty_name %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>