config/routes.rb
Hive::Application.routes.draw do
  resources :kpi_cou_rels

  resources :types

  resources :kpis

  resources :counters

  resources :vendors

  resources :measurements

  resources :adapters do
	resources :measurements
  end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	has_many :measurements, dependent: :destroy
	has_many :counters, :through => :measurement
	validates_presence_of :ve_name
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vendor }
      else
        format.html { render action: 'new' }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:ve_id, :ve_name)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :ve_name %><br>
    <%= f.text_field :ve_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<h1>Listing vendors</h1>

<table>
  <thead>
    <tr>
      <th>Ve</th>
      <th>Ve name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.id %></td>
        <td><%= vendor.ve_name %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ve:</strong>
  <%= @vendor.id %>
</p>

<p>
  <strong>Ve name:</strong>
  <%= @vendor.ve_name %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>