config/routes.rb
Hive::Application.routes.draw do
  resources :kpi_cou_rels

  resources :types

  resources :kpis

  resources :counters

  resources :vendors

  resources :measurements

  resources :adapters do
	resources :measurements
  end

end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
	belongs_to :adapter
	belongs_to :vendor
	has_many :counters, dependent: :destroy
	validates_presence_of :me_name
	validates_presence_of :me_table
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:show, :edit, :update, :destroy]

  # GET /measurements
  # GET /measurements.json
  def index
    @measurements = Measurement.all
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
  end

  # GET /measurements/new
  def new
    @measurement = Measurement.new
  end

  # GET /measurements/1/edit
  def edit
  end

  # POST /measurements
  # POST /measurements.json
  def create
	puts measurement_params
    #@adapter = Adapter.find(measurement_params[:adapter_id])
    #@vendor = Vendor.find(measurement_params[:vendor_id])
    @measurement = Measurement.new(measurement_params)
    #@measurement = Measurement.create()


    #@order = Order.create(:order_date => Time.now, :customer_id => @customer.id)

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @measurement }
      else
        format.html { render action: 'new' }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurements/1
  # PATCH/PUT /measurements/1.json
  def update
    respond_to do |format|
      if @measurement.update(measurement_params)
        format.html { redirect_to @measurement, notice: 'Measurement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement.destroy
    respond_to do |format|
      format.html { redirect_to measurements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurement_params
      params.require(:measurement).permit(:vendor_id, :adapter_id, :me_name, :me_table)
    end
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/measurements/_form.html.erb
<%= form_for(@measurement) do |f| %>
  <% if @measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measurement.errors.count, "error") %> prohibited this measurement from being saved:</h2>

      <ul>
      <% @measurement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :vendor_id %><br>
    <%= f.number_field :vendor_id %>
  </div>
  <div class="field">
    <%= f.label :adapter_id %><br>
    <%= f.number_field :adapter_id %>
  </div>
  <div class="field">
    <%= f.label :me_name %><br>
    <%= f.text_field :me_name %>
  </div>
  <div class="field">
    <%= f.label :me_table %><br>
    <%= f.text_field :me_table %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/measurements/edit.html.erb
<h1>Editing measurement</h1>

<%= render 'form' %>

<%= link_to 'Show', @measurement %> |
<%= link_to 'Back', measurements_path %>

app/views/measurements/index.html.erb
<h1>Listing measurements</h1>

<table>
  <thead>
    <tr>
      <th>Me</th>
      <th>Ve</th>
      <th>Ad</th>
      <th>Me name</th>
      <th>Me table</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @measurements.each do |measurement| %>
      <tr>
        <td><%= measurement.id %></td>
        <td><%= measurement.vendor_id %></td>
        <td><%= measurement.adapter_id %></td>
        <td><%= measurement.me_name %></td>
        <td><%= measurement.me_table %></td>
        <td><%= link_to 'Show', measurement %></td>
        <td><%= link_to 'Edit', edit_measurement_path(measurement) %></td>
        <td><%= link_to 'Destroy', measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Measurement', new_measurement_path %>

app/views/measurements/new.html.erb
<h1>New measurement</h1>

<%= render 'form' %>

<%= link_to 'Back', measurements_path %>

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Me:</strong>
  <%= @measurement.id %>
</p>

<p>
  <strong>Ve:</strong>
  <%= @measurement.vendor_id %>
</p>

<p>
  <strong>Ad:</strong>
  <%= @measurement.adapter_id %>
</p>

<p>
  <strong>Me name:</strong>
  <%= @measurement.me_name %>
</p>

<p>
  <strong>Me table:</strong>
  <%= @measurement.me_table %>
</p>

<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>