config/routes.rb
Hive::Application.routes.draw do
  resources :kpi_cou_rels

  resources :types

  resources :kpis

  resources :counters

  resources :vendors

  resources :measurements

  resources :adapters do
	resources :measurements
  end

end

app/models/adapter.rb
class Adapter < ActiveRecord::Base
	has_many :measurements, dependent: :destroy
	has_many :counters, :through => :measurement
	validates_presence_of :ad_name
end

app/controllers/adapters_controller.rb
class AdaptersController < ApplicationController
  before_action :set_adapter, only: [:show, :edit, :update, :destroy]

  # GET /adapters
  # GET /adapters.json
  def index
    @adapters = Adapter.all
  end

  # GET /adapters/1
  # GET /adapters/1.json
  def show
  end

  # GET /adapters/new
  def new
    @adapter = Adapter.new
  end

  # GET /adapters/1/edit
  def edit
  end

  # POST /adapters
  # POST /adapters.json
  def create
    @adapter = Adapter.new(adapter_params)

    respond_to do |format|
      if @adapter.save
        format.html { redirect_to @adapter, notice: 'Adapter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @adapter }
      else
        format.html { render action: 'new' }
        format.json { render json: @adapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adapters/1
  # PATCH/PUT /adapters/1.json
  def update
    respond_to do |format|
      if @adapter.update(adapter_params)
        format.html { redirect_to @adapter, notice: 'Adapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @adapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adapters/1
  # DELETE /adapters/1.json
  def destroy
    @adapter.destroy
    respond_to do |format|
      format.html { redirect_to adapters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adapter
      @adapter = Adapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adapter_params
      params.require(:adapter).permit(:ad_id, :ad_name)
    end
end

app/helpers/adapters_helper.rb
module AdaptersHelper
end

app/views/adapters/_form.html.erb
<%= form_for(@adapter) do |f| %>
  <% if @adapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adapter.errors.count, "error") %> prohibited this adapter from being saved:</h2>

      <ul>
      <% @adapter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ad_name %><br>
    <%= f.text_field :ad_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adapters/edit.html.erb
<h1>Editing adapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @adapter %> |
<%= link_to 'Back', adapters_path %>

app/views/adapters/index.html.erb
<h1>Listing adapters</h1>

<table>
  <thead>
    <tr>
      <th>Ad</th>
      <th>Ad name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @adapters.each do |adapter| %>
      <tr>
        <td><%= adapter.ad_name %></td>
        <td><%= link_to 'Show', adapter %></td>
        <td><%= link_to 'Edit', edit_adapter_path(adapter) %></td>
        <td><%= link_to 'Destroy', adapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adapter', new_adapter_path %>

app/views/adapters/new.html.erb
<h1>New adapter</h1>

<%= render 'form' %>

<%= link_to 'Back', adapters_path %>

app/views/adapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ad name:</strong>
  <%= @adapter.ad_name %>
</p>

<%= link_to 'Edit', edit_adapter_path(@adapter) %> |
<%= link_to 'Back', adapters_path %>